[package]
name = "aio-translator-original"
edition.workspace = true
version.workspace = true
publish = false


[dependencies]
aio-translator-interface.workspace = true
reqwest.workspace = true
anyhow.workspace = true
